checkpoint_dir: '$ROOT_DIR/training/checkpoints/'
log_dir: '$ROOT_DIR/training/logs/'
output_save_path: '$ROOT_DIR/training/results/'
dataset_dir: '$ROOT_DIR/data/stl10/'
max_epoch: 300
batch_size: 64
learning_rate: 1e-3
learning_rate_probing: 1e-3
probing_epoch: 10
num_workers: 4
dataset: 'stl10'
random_seed: 1
